# Generated by Django 6.0.7 on 2026-07-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name', 'id']},
        ),
    ]
